### ISSUE TITLE
设置--do_predict为True运行代码出错

### ISSUE THREAD

**Issue by HANSZJH** [LiYuxin321/TMDM#1]
您好，请问设置--do_predict为True运行代码后，在
            if args.do_predict:
                print('>>>>>>>predicting : {}<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<'.format(setting))
                exp.predict(setting, True)
这里时报错：
>>>>>>>predicting : MineData_MineData_custom_ftS_sl96_ll48_pl192_dm512_nh8_el2_dl1_df2048_fc3_ebtimeF_dtTrue_Exp_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
pred 1
Traceback (most recent call last):
  File "D:\onedrive\桌面\TMDM2\runner9_NS_transformer.py", line 166, in <module>
    torch.cuda.empty_cache()
        ^^^^^^^^^^^^^^^^^^^^^
  File "D:\onedrive\桌面\TMDM2\model9_NS_transformer\exp\exp_main.py", line 606, in predict
    outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\anaconda3\Lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Model.forward() missing 2 required positional arguments: 'y_0_hat' and 't'

进程已结束，退出代码为 1
这是什么原因，请问您遇到过吗

**Comment by HANSZJH** [comment]
这里使用的时我自己的数据集，为单变量模式

**Comment by HANSZJH** [comment]
使用代码提供的数据集，未修改其他参数，只修改do_predict为True，也是报错。无法运行

**Comment by LiYuxin321** [comment]
You don't need to use this parameter. Please read the code carefully; the prediction will work even if this variable is not modified. If you are using your own dataset, you will need to adjust the input dimensions and several other parameters.

**Comment by HANSZJH** [comment]
感谢您的回复， 可是我在runner9_NS_transformer.py中发现
            if args.do_predict:
                print('>>>>>>>predicting : {}<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<'.format(setting))
                exp.predict(setting, True)
这是否表示需要将do_predict改为True才可以进行预测。

此外，我听从您的回复，只修改维度这些参数:
    parser.add_argument('--enc_in', type=int, default=1, help='encoder input size')
    parser.add_argument('--dec_in', type=int, default=1, help='decoder input size')
    parser.add_argument('--c_out', type=int, default=1, help='output size')
并且修改model9_NS_transformer/diffusion_models/model.py中的维度：
class ConditionalGuidedModel(nn.Module):
    def __init__(self, config, MTS_args):
        super(ConditionalGuidedModel, self).__init__()
        n_steps = config.diffusion.timesteps + 1
        self.cat_x = config.model.cat_x
        self.cat_y_pred = config.model.cat_y_pred
        data_dim = 2

        self.lin1 = ConditionalLinear(data_dim, 128, n_steps)
        self.lin2 = ConditionalLinear(128, 128, n_steps)
        self.lin3 = ConditionalLinear(128, 128, n_steps)
        self.lin4 = nn.Linear(128, 1)
我使用的单变量数据集，且没有修改其他参数，得到结果如下：
Testing: 375/380 cost time: 0.452984 min
test shape: (380, 4, 192, 1) (380, 4, 192, 1)
test shape: (1520, 192, 1) (1520, 192, 1)
NT metrc: mse:0.3807, mae:0.4893 , rmse:0.6170, mape:1.8860, mspe:228.7337
CARD metrc: QICE:4.7000%, PICP:75.5171%
CRPS 0.36281094839380595 CRPS_sum 0.36281094839380595

进程已结束，退出代码为 0
并没有运行
exp.predict(setting, True)这是为什么

**Comment by HANSZJH** [comment]
您好，我发现exe_main.py中您在使用self.model时很多地方outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark)
只输入了四个参数，而model = diffuMTS.Model(self.args, self.device).float()中
    def forward(self, x, x_mark, y, y_t, y_0_hat, t):
        enc_out = self.enc_embedding(x, x_mark)
        dec_out = self.diffussion_model(enc_out, y_t, y_0_hat, t)
        return dec_out
这里需要的是六个参数。
此外在您定义的predict(self, setting, load=False)中：
outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark)也是传入四个参数。
想请问是我理解错误还是代码有点问题

**Comment by LiYuxin321** [comment]
You have already run the final result, you do not need to run exp.predict(setting, True).

**Comment by HANSZJH** [comment]
所以代码只能进行进行训练和测试不能下一步的预测了吗？
            if args.do_predict:
                print('>>>>>>>predicting : {}<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<'.format(setting))
                exp.predict(setting, True)
这一段的意义和Dataset_Pred是做什么的

**Comment by HANSZJH** [comment]
请问想要预测时序是不是需要再自己编写一段代码用来预测。您提供的方法在我使用时，若不修改只有train, vaild, test可以运行，还是我在哪一步使用错误了

**Comment by HANSZJH** [comment]
另外：
if args.is_training = False
下一步也无法执行,即

>     else:
        ii = 0
        setting = '{}_{}_{}_ft{}_sl{}_ll{}_pl{}_dm{}_nh{}_el{}_dl{}_df{}_fc{}_eb{}_dt{}_{}_{}'.format(args.model_id,
                                                                                                      args.model,
                                                                                                      args.data,
                                                                                                      args.features,
                                                                                                      args.seq_len,
                                                                                                      args.label_len,
                                                                                                      args.pred_len,
                                                                                                      args.d_model,
                                                                                                      args.n_heads,
                                                                                                      args.e_layers,
                                                                                                      args.d_layers,
                                                                                                      args.d_ff,
                                                                                                      args.factor,
                                                                                                      args.embed,
                                                                                                      args.distil,
                                                                                                      args.des, ii)

        exp = Exp(args)  # set experiments
        print('>>>>>>>testing : {}<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<'.format(setting))
        # exp.test_cond(setting, test=1)
        exp.test(setting, test=1)
        torch.cuda.empty_cache()

**Comment by HANSZJH** [comment]
不好意思，我的代码基础可能比较弱，恳请您指导问题

**Comment by HANSZJH** [comment]
我尝试在数据集末尾添加需要新增的预测日期并且赋值为np.nan，能够通过test得到结果。请问这种方法可行吗

**Comment by Jokerandfisher** [comment]
You mentioned that the code above has already been run to get the results. I have doubts about the writing meaning of 
"if args.do_predict: print('>>>>>>>predicting : {}<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<'.format(setting)) exp.predict(setting, True)".
 I hope to get your answer.
